In [7]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import pickle

embeddings_file = f'/home/jixian/github/suchka-ai/output/faces/Joanna Angel/embeddings.pickle'
with open(embeddings_file, 'rb') as file: 
    embeddings = pickle.load(file)

new_embeddings = {}    
for k,v in embeddings.items():
    # print(k, type(v), len(v))
    if type(v) == tuple:        
        new_embeddings[k] = list(v)[0]
    else:
        new_embeddings[k] = v
        
def convert_dict_to_matrix(dictionary):
    keys = list(dictionary.keys())
    num_rows = len(dictionary)
    num_cols = max(len(values) for values in dictionary.values())
    matrix = np.zeros((num_rows, num_cols))    
    for i, key in enumerate(keys):
        values = dictionary[key]
        print(type(values), values)
        if type(values) == tuple:
            values = list(values)[0]                
        matrix[i, :len(values)] = values
    return matrix
    
# print(embeddings)    
emd = np.array(list(embeddings.values())[0])
# embeddings = [np.array(x) for x in list(embeddings.values())]
# print(type(embeddings))
embeddings = convert_dict_to_matrix(embeddings)
# print(embeddings)
# print(emd)
score = cosine_similarity([emd], embeddings)
print(score)


<class 'list'> [0.004156163893640041, -0.008669150993227959, 0.009043853729963303, 0.0028461506590247154, -0.012913241051137447, 0.021175451576709747, -0.002386955078691244, 0.019641675055027008, 0.01725335791707039, 0.013619797304272652, 0.019614296033978462, -0.0016424376517534256, 0.003475212026387453, 0.012447912245988846, 0.0034577222540974617, -0.018842268735170364, 0.015671009197831154, 0.015828615054488182, 0.02287359908223152, 0.023983117192983627, 0.01898069679737091, 0.011023800820112228, 0.009682866744697094, 0.015720553696155548, -0.0005825867410749197, -0.01322535052895546, 0.015822237357497215, 0.0007593648042529821, -0.008141648024320602, 0.036422643810510635, 0.01507757231593132, 0.008589683100581169, -0.008966568857431412, 0.029621541500091553, -0.005474896635860205, 0.0007206619484350085, 0.004660303704440594, -0.015843139961361885, 0.017146261408925056, 0.016266049817204475, 0.00035843299701809883, 0.00582103943452239, 0.011540117673575878, -0.011823156848549843, -0

In [9]:
my_list = [
    {"path": "/dir1", "is_solo": False},
    {"path": "/dir2", "is_solo": True},
    {"path": "/dir3", "is_solo": True},
    {"path": "/dir4", "is_solo": False},
]

sorted_list = sorted(my_list, key=lambda x: x["is_solo"], reverse=True)
print(sorted_list)

[{'path': '/dir2', 'is_solo': True}, {'path': '/dir3', 'is_solo': True}, {'path': '/dir1', 'is_solo': False}, {'path': '/dir4', 'is_solo': False}]


In [23]:
import numpy as np

def convert_dict_to_matrix(dictionary):
    keys = list(dictionary.keys())
    num_rows = len(dictionary)
    num_cols = max(len(values) for values in dictionary.values())

    matrix = np.zeros((num_rows, num_cols))

    for i, key in enumerate(keys):
        values = dictionary[key]
        matrix[i, :len(values)] = values

    return matrix

# Example dictionary
dictionary = {
    'key1': [1.0, 2.0, 3.0],
    'key2': [4.0, 5.0],
    'key3': [6.0, 7.0, 8.0, 9.0]
}

# Convert dictionary to matrix
matrix = convert_dict_to_matrix(dictionary)
print(matrix)

[[1. 2. 3. 0.]
 [4. 5. 0. 0.]
 [6. 7. 8. 9.]]
