In [1]:
#!/usr/bin/env python3
import os
import sys

project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.append(project_root)

from core.tag.tag import TagAnalysis

tag = TagAnalysis()
tag.data_matrix

X_tensor:
[[1 0 1 0 0 0]
 [1 0 0 0 1 0]
 [1 1 0 0 0 1]
 [0 0 1 1 0 0]
 [0 0 0 1 1 0]] torch.Size([5, 6])
y_tensor:
[[0 0 1 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 0 1 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 0 0 1]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 1 0 0]] torch.Size([11, 6])


ValueError: Using a target size (torch.Size([11, 1])) that is different to the input size (torch.Size([5, 6])) is deprecated. Please ensure they have the same size.